services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  backend_app:
    build: ./backend
    command: npx nodemon index.js
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8800:8800"
    environment:
      DB_HOST: mysql_db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: test
    depends_on:
      - mysql_db
    networks:
      - app_network

  frontend_app:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://backend_app:8800
    depends_on:
      - backend_app
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
